CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS items (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE,
  price NUMERIC NOT NULL DEFAULT 0,
  date_registered DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_in (
  id SERIAL PRIMARY KEY,
  item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  qty INTEGER NOT NULL,
  date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_out (
  id SERIAL PRIMARY KEY,
  item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  client_name TEXT,
  unit_price NUMERIC NOT NULL,
  qty INTEGER NOT NULL,
  total NUMERIC NOT NULL,
  date DATE NOT NULL
);
